version: 0.2

phases:
  install:
    commands:
      - which curl || (apt-get update && apt-get install -y curl)
  pre_build:
    commands:
  build:
    commands:
      - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo $CODEBUILD_START_TIME
      - >
        curl --location 'https://webapi.coralogix.com/api/v1/external/tags/' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer $API_KEY \
          --data '{     
              "name": "'"$CODEBUILD_RESOLVED_SOURCE_VERSION"'",
              "application": ["aws"],
              "subsystem": ["tag-build"]
          }'
