version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - >
        curl --location 'https://webapi.coralogix.com/api/v1/external/tags/' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer '"$API_KEY" \
          --data '{     
              "name": "'"$CODEBUILD_RESOLVED_SOURCE_VERSION"'",
              "application": ["aws"],
              "subsystem": ["tag-build"]
          }'
