version: 0.2

phases:
  install:
    commands:
      - which curl || (apt-get update && apt-get install -y curl)
  pre_build:
    commands:
  build:
    commands:
      # Replace <CORALOGIX_TAGS_API_ENDPOINT> with the actual endpoint URL
      # Ensure your JSON body structure matches what your API expects
      - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo $CODEBUILD_START_TIME
      - >
        curl -X POST "https://webapi.coralogix.com/api/v1/external/tags/"
        -H "Authorization: Bearer $API_KEY"
        -H "Content-Type: application/json"
        -d '{
          "timestamp": "'"$CODEBUILD_START_TIME"'",
          "name": "'"$CODEBUILD_RESOLVED_SOURCE_VERSION"'",
          "applications": ["aws"]
        }'
